spring:
    profiles: native
fdfs:
  web-server-url: 192.168.2.132
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
  - 192.168.2.132:22122
---
spring:
     profiles: dev
fdfs:
  web-server-url: 192.168.2.84:28888
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
  - 192.168.2.84:22122